language: c

compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get update
  - sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev
install:
  - echo  "Reached Install Section"
  - sudo apt-get install -qq gcc-avr binutils-avr avr-libc
  - sudo apt-get install avrdude

script:
  - echo "Reached Script Section"
  #- gcc degree/degree.c degree/main.c -o output -lcunit
  #- gcc CUnit_activity3.c -o output -lcunit
  #- ./output
  #- avr-gcc -Os -DF_CPU=16000000UL -mmcu=atmega328p -c -o distance.o Distance_warning/distance.c
  #- avr-gcc -mmcu=atmega328p distance_warning.o -o distance_warning
  #- avr-gcc -mmcu=atmega328p distance.o -o distance
  #- avr-objcopy -O ihex -R .eeprom distance_warning distance_warning.hex
  #- avr-objcopy -O ihex -R .eeprom distance distance.hex
  - avr-gcc -Os -DF_CPU=16000000UL -mmcu=atmega328p -c -o buzzer.o ECS/buzzer.c
  - avr-gcc -Os -DF_CPU=16000000UL -mmcu=atmega328p -c -o distance.o ECS/distance.c
  - avr-gcc -Os -DF_CPU=16000000UL -mmcu=atmega328p -c -o main.o ECS/main.c
  - avr-gcc -mmcu=atmega328p buzzer.o distance.o main.o -o proj
  - avr-objcopy -O ihex -R .eeprom project project.hex

